# Generated by Django 5.0.2 on 2024-07-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginformation',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
