# Generated by Django 5.0.2 on 2024-07-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listinginformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginformation',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
