# Generated by Django 5.0.2 on 2024-07-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidPrice',
            new_name='bidInitialPrice',
        ),
    ]
