# Generated by Django 5.0.2 on 2024-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bidprice_bid_bidinitialprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidInitialPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='listinginformation',
            old_name='price',
            new_name='bidInitialPrice',
        ),
    ]
