# Generated by Django 5.0.2 on 2024-07-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bidinitialprice_bid_bidprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listinginformation',
            old_name='bidInitialPrice',
            new_name='bidCurrentPrice',
        ),
    ]
