# Generated by Django 5.0.2 on 2024-07-08 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bidinitialprice_listinginformation_bidcurrentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginformation',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
