# Generated by Django 5.0.2 on 2024-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginformation',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
